### ISSUE TITLE
I don't understand what I should write in <TAG>

### ISSUE THREAD

**Issue by JeroenGar** [mediasuitenz/docker-overpass-api#3]
Hello, I need my own overpass api server for a school project, but I don't know what i should put at <TAG>. I've tried a few different things and i always get the same error. Can you help me?

```
Reading XML file ... elapsed node 2689629970. /srv/osm3s/bin/init_osm3s.sh: line 44:     9 Broken pipe             bunzip2 < $PLANET_FILE
        10 Killed                  | $EXEC_DIR/bin/update_database --db-dir=$DB_DIR/ $META $COMPRESSION
The command '/bin/sh -c /srv/osm3s/bin/init_osm3s.sh "$PLANET_FILE" "$DB_DIR" "$EXEC_DIR"   && rm -f "$PLANET_FILE"' returned a non-zero code: 137
```

**Comment by tfentonz** [comment]
I've removed the `<TAG>` from the docker commands in [README.md.](https://github.com/mediasuitenz/docker-overpass-api/blob/master/README.md)

When running `docker build` it will apply the _latest_ tag to the newly built image. `<TAG>` could be anything you like such as a name, version, hash, or timestamp.
